export default [
    {name: "Arsenal", logo: "http"},
    {name: "Aston Villa", logo: "http"},
    {name: "Brighton", logo: "http"},
    {name: "Brentford", logo: "http"},
    {name: "Burnley", logo: "http"},
    {name: "Chelsea", logo: "http"},
    {name: "Crystal Palace", logo: "http"},
    {name: "Liverpool", logo: "http"},
    {name: "Man City", logo: "http"},
    {name: "Man United", logo: "http"},
    {name: "Everton", logo: "http"},
    {name: "Leeds", logo: "http"},
    {name: "Leicester", logo: "http"},
    {name: "Watford", logo: "http"},
    {name: "Norwich", logo: "http"},
    {name: "Newcastle", logo: "http"},
    {name: "Southampton", logo: "http"},
    {name: "Tottenham", logo: "http"},
    {name: "West Ham", logo: "http"},
    {name: "Wolves", logo: "http"},
  ]