export default [
    {name: "Arsenal", logo: "/logo/arsenal.png"},
    {name: "Aston Villa", logo: "/logo/astonvilla.png"},
    {name: "Brentford", logo: "/logo/brentford.png"},
    {name: "Burnley", logo: "/logo/burnley.jpg"},
    {name: "Brighton", logo: "/logo/brighton.png"},
    {name: "Chelsea", logo: "/logo/chelsea.png"},
    {name: "Crystal Palace", logo: "/logo/crystalpalace.png"},
    {name: "Everton", logo: "/logo/everton.png"},
    {name: "Fulham", logo: "/logo/fulham.png"},
    {name: "Leeds", logo: "/logo/leeds.png"},
    {name: "Leicester", logo: "/logo/leicester.png"},
    {name: "Liverpool", logo: "/logo/liverpool.png"},
    {name: "Man City", logo: "/logo/mancity.png"},
    {name: "Man United", logo: "/logo/manutd.png"},
    {name: "Watford", logo: "/logo/wat.png"},
    {name: "Newcastle", logo: "/logo/newcastle.png"},
    {name: "Norwich", logo: "/logo/norwich.png"},
    {name: "Southampton", logo: "/logo/southampton.png"},
    {name: "Tottenham", logo: "/logo/tottenham.png"},
    {name: "West Ham", logo: "/logo/westham.png"},
    {name: "Wolves", logo: "/logo/wolves.png"},
  ]